# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run lambda container
      - name: Run lambda container
        uses: docker://lambci/lambda:build-python3.8
        with:
          args: /bin/sh -c "mkdir python_lib && pip install -r requirements.txt -t /python_lib/ && ls"
      
      - name: Zip Python libraries
        run: zip -r9 python_lib.zip ./python
      
      - name: List Files
        run: ls
